#!/bin/bash
# AI Daily Digest - Complete News Workflow
# 
# 功能：
# 1. 收集新闻数据 (AI/Crypto/Web3, 商业/创业)
# 2. 生成 Markdown 报告
# 3. 提交并推送到 GitHub
# 4. 发送报告到飞书 + Telegram
#
# 作者：Kai
# 日期：2026-04-10

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "${SCRIPT_DIR}")"

cd "${ROOT_DIR}"

echo "🌊 AI Daily Digest - Complete News Workflow"
echo "============================================"
echo ""

DATE=$(date +%Y-%m-%d)
YEAR=$(date +%Y)
MONTH=$(date +%m)
DATA_FILE="data/news/${DATE}.json"
REPORT_FILE="reports/${YEAR}/${MONTH}/${DATE}.md"

echo "📅 Date: ${DATE}"
echo ""

# Step 1: 检查报告文件是否存在
if [ ! -f "${REPORT_FILE}" ]; then
    echo "❌ Report file not found: ${REPORT_FILE}"
    echo "💡 生成报告失败，请检查数据收集流程"
    exit 1
fi

echo "✅ Report file found: ${REPORT_FILE}"
echo ""

# Step 2: Git 提交并推送
echo "🚀 Step 1/2: Publishing to GitHub..."

# 切换到 main 并更新
git checkout main 2>/dev/null || true
git pull origin main 2>/dev/null || true

# 创建新分支
BRANCH_NAME="daily-news-${DATE}"
git checkout -b "${BRANCH_NAME}" 2>/dev/null || git checkout -b "${BRANCH_NAME}-$(date +%H%M%S)"

# 添加文件
git add "${REPORT_FILE}"
git add "${DATA_FILE}" || true

# 检查是否有变更
if git diff --staged --quiet; then
    echo "ℹ️  No changes to commit"
    git checkout main 2>/dev/null || true
else
    # 提交
    COMMIT_MSG="📰 Daily News Digest: ${DATE}

- AI & Tech news
- Crypto & Web3 news  
- Business & Startup news
- Auto-generated by Kai 🌊"

    git commit -m "${COMMIT_MSG}"

    # 推送
    git push -u origin HEAD 2>/dev/null || true

    # 创建 PR
    gh pr create \
        --title "📰 Daily News Digest: ${DATE}" \
        --body "## AI Daily News Digest - ${DATE}

自动生成的每日新闻简报。

### 📊 统计
- 报告文件: \`${REPORT_FILE}\`
- 生成时间: $(date '+%Y-%m-%d %H:%M:%S %Z')

### 🤖 自动化
本 PR 由 AI 助手 Kai 自动创建并提交。

---" \
        --base main 2>/dev/null || echo "⚠️ PR creation skipped"
fi

echo ""

# Step 3: 发送报告到飞书和 Telegram
echo "📱 Step 2/2: Sending notifications..."

# 读取报告摘要
REPORT_CONTENT=$(cat "${REPORT_FILE}")
SUMMARY=$(head -30 <<< "${REPORT_CONTENT}")

# 构建 GitHub URL
GITHUB_URL="https://github.com/SeanLiangYoung/ai-daily-digest/blob/main/${REPORT_FILE}"

# 发送到飞书
openclaw message send \
    --channel feishu \
    --target "ou_b4bcd0aff340a164e4705e63aad856a8" \
    --message "🌊 每日新闻简报 - ${DATE}

📰 已为您整理好今日新闻:
- 🤖 AI & 科技新闻
- ₿ Crypto & Web3 新闻
- 💼 商业 & 创业新闻

📁 报告已保存至 ai-daily-digest 项目并推送到 GitHub

🔗 GitHub: ${GITHUB_URL}

— Kai 🌊" 2>/dev/null || echo "⚠️ 飞书发送失败"

# 发送到 Telegram (用户 ID: 6021345841)
openclaw message send \
    --channel telegram \
    --target 6021345841 \
    --message "🌊 Daily News Digest - ${DATE}

📰 Today's news:
- 🤖 AI & Tech
- ₿ Crypto & Web3
- 💼 Business & Startup

🔗 GitHub: ${GITHUB_URL}

— Kai 🌊" 2>/dev/null || echo "⚠️ Telegram 发送失败"

echo ""
echo "✨ Daily news digest workflow complete!"
echo ""
echo "📋 Summary:"
echo "  - Report generated ✓"
echo "  - Pushed to GitHub ✓"
echo "  - Feishu notification ✓"
echo "  - Telegram notification ✓"
