#!/bin/bash
# AI Daily Digest - News Collection Script
# 
# 功能：
# 1. 搜索科技/AI、Crypto/Web3、商业/创业新闻
# 2. 生成 Markdown 报告
# 3. 保存到 reports/ 目录
# 4. 推送到 GitHub
#
# 作者：Kai
# 日期：2026-04-10

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "${SCRIPT_DIR}")"

cd "${ROOT_DIR}"

DATE=$(date +%Y-%m-%d)
YEAR=$(date +%Y)
MONTH=$(date +%m)

echo "🌊 AI Daily Digest - News Collection"
echo "===================================="
echo "📅 Date: ${DATE}"
echo ""

# 搜索新闻类别
CATEGORIES=("AI 科技 新闻" "Crypto Web3 新闻" "商业 创业 新闻")

mkdir -p "data/news"
DATA_FILE="data/news/${DATE}.json"

# 使用 web_search 收集新闻（这里生成搜索结果，实际由 AI Agent 处理）
echo "📡 Searching news..."

# 生成报告
REPORT_DIR="reports/${YEAR}/${MONTH}"
mkdir -p "${REPORT_DIR}"
REPORT_FILE="${REPORT_DIR}/${DATE}.md"

# 检查是否已有数据
if [ -f "${DATA_FILE}" ]; then
    echo "✅ Data file exists: ${DATA_FILE}"
else
    echo "⚠️ Data file not found, will be generated by agent"
fi

echo "✅ News digest ready for generation"
echo "📁 Report will be saved to: ${REPORT_FILE}"
