#!/bin/bash
# AI Daily Digest - Git Publish Script
# 
# 功能：
# 1. 直接提交到 main 分支
#
# 作者：Kai
# 日期：2026-03-08
# 更新：2026-04-15 改为直接提交到 main

set -e  # 遇到错误立即退出

# 颜色输出
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🤖 AI Daily Digest - Git Publish${NC}"
echo "===================================="
echo ""

# 获取今天日期
DATE=$(date +%Y-%m-%d)

echo -e "${BLUE}📅 Date: ${DATE}${NC}"
echo ""

# 检查是否在 git 仓库中
if [ ! -d ".git" ]; then
    echo -e "${RED}❌ Error: Not in a git repository${NC}"
    exit 1
fi

# 检查报告文件是否存在
YEAR=$(date +%Y)
MONTH=$(date +%m)
REPORT_FILE="reports/${YEAR}/${MONTH}/${DATE}.md"

if [ ! -f "${REPORT_FILE}" ]; then
    echo -e "${RED}❌ Error: Report file not found: ${REPORT_FILE}${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Report file found: ${REPORT_FILE}${NC}"
echo ""

# 切换到 main 分支并更新
echo -e "${BLUE}📥 Updating main branch...${NC}"
git checkout main
git pull origin main

# 添加文件
echo -e "${BLUE}📦 Staging files...${NC}"
git add "${REPORT_FILE}"
git add data/ || true
git add data/news/ || true

# 检查是否有变更
if git diff --staged --quiet; then
    echo -e "${BLUE}ℹ️  No changes to commit${NC}"
    exit 0
fi

# 提交
COMMIT_MSG="📊 Daily digest: ${DATE}

- AI & Tech news
- Crypto & Web3 news  
- Business & Startup news
- Auto-generated by Kai 🌊"

echo -e "${BLUE}💾 Committing to main...${NC}"
git commit -m "${COMMIT_MSG}"

# 推送
echo -e "${BLUE}🚀 Pushing to main...${NC}"
git push origin main

echo ""
echo -e "${GREEN}✨ Publish complete!${NC}"
echo ""
echo "📋 Summary:"
echo "  - Report committed to main"
echo "  - Pushed to GitHub"