#!/bin/bash
# AI Daily Digest - Complete News Workflow
# 
# 功能：
# 1. 收集新闻数据 (AI/Crypto/Web3, 商业/创业)
# 2. 生成 Markdown 报告
# 3. 提交并推送到 GitHub
# 4. 发送报告到飞书
#
# 注意：实际新闻收集由 AI Agent (cron) 执行
#
# 作者：Kai
# 日期：2026-04-10

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "${SCRIPT_DIR}")"

cd "${ROOT_DIR}"

DATE=$(date +%Y-%m-%d)
YEAR=$(date +%Y)
MONTH=$(date +%m)
DATA_FILE="data/news/${DATE}.json"
REPORT_FILE="reports/${YEAR}/${MONTH}/${DATE}.md"

echo "🌊 AI Daily Digest - Git Publish Workflow"
echo "=========================================="
echo "📅 Date: ${DATE}"
echo ""

# 检查报告文件
if [ ! -f "${REPORT_FILE}" ]; then
    echo "❌ Report file not found: ${REPORT_FILE}"
    echo "💡 Please run the cron task first to generate the report"
    exit 1
fi

echo "✅ Report file found: ${REPORT_FILE}"
echo ""

# Step 1: Git 提交并推送
echo "🚀 Step 1/2: Publishing to GitHub..."

# 切换到 main 并更新
git checkout main
git pull origin main

# 创建新分支
BRANCH_NAME="daily-news-${DATE}"
git checkout -b "${BRANCH_NAME}" 2>/dev/null || git checkout -b "${BRANCH_NAME}-$(date +%H%M%S)"

# 添加文件
git add "${REPORT_FILE}"
git add "${DATA_FILE}" || true

# 检查是否有变更
if git diff --staged --quiet; then
    echo "ℹ️  No changes to commit"
    git checkout main
    exit 0
fi

# 提交
COMMIT_MSG="📰 Daily News Digest: ${DATE}

- AI & Tech news
- Crypto & Web3 news  
- Business & Startup news
- Auto-generated by Kai 🌊"

git commit -m "${COMMIT_MSG}"

# 推送
git push -u origin HEAD

# 创建 PR
gh pr create \
    --title "📰 Daily News Digest: ${DATE}" \
    --body "## AI Daily News Digest - ${DATE}

自动生成的每日新闻简报。

### 📊 统计
- 报告文件: \`${REPORT_FILE}\`
- 生成时间: $(date '+%Y-%m-%d %H:%M:%S %Z')

### 🤖 自动化
本 PR 由 AI 助手 Kai 自动创建并提交。

---" \
    --base main 2>/dev/null || echo "⚠️ PR creation skipped (may already exist)"

echo ""

# Step 2: 确认完成
echo "✅ Git publish complete!"
echo ""
echo "📋 Summary:"
echo "  - Report generated ✓"
echo "  - Pushed to GitHub ✓"
