#!/bin/bash
# AI Daily Digest - Git Publish Script
# 
# 功能：
# 1. 创建新分支
# 2. 提交今日报告
# 3. 推送并创建 PR
#
# 作者：Kai
# 日期：2026-03-08

set -e  # 遇到错误立即退出

# 颜色输出
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🤖 AI Daily Digest - Git Publish${NC}"
echo "===================================="
echo ""

# 获取今天日期
DATE=$(date +%Y-%m-%d)
BRANCH_NAME="daily-digest-${DATE}"

echo -e "${BLUE}📅 Date: ${DATE}${NC}"
echo -e "${BLUE}🌿 Branch: ${BRANCH_NAME}${NC}"
echo ""

# 检查是否在 git 仓库中
if [ ! -d ".git" ]; then
    echo -e "${RED}❌ Error: Not in a git repository${NC}"
    exit 1
fi

# 检查报告文件是否存在
YEAR=$(date +%Y)
MONTH=$(date +%m)
REPORT_FILE="reports/${YEAR}/${MONTH}/${DATE}.md"

if [ ! -f "${REPORT_FILE}" ]; then
    echo -e "${RED}❌ Error: Report file not found: ${REPORT_FILE}${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Report file found: ${REPORT_FILE}${NC}"
echo ""

# 切换到 main 分支并更新
echo -e "${BLUE}📥 Updating main branch...${NC}"
git checkout main
git pull origin main

# 创建新分支
echo -e "${BLUE}🌿 Creating branch: ${BRANCH_NAME}${NC}"
git checkout -b "${BRANCH_NAME}"

# 添加文件
echo -e "${BLUE}📦 Staging files...${NC}"
git add "${REPORT_FILE}"
git add data/ || true  # 如果 data/ 目录存在

# 检查是否有变更
if git diff --staged --quiet; then
    echo -e "${BLUE}ℹ️  No changes to commit${NC}"
    git checkout main
    git branch -D "${BRANCH_NAME}"
    exit 0
fi

# 提交
COMMIT_MSG="📊 Daily digest: ${DATE}

- Collected tweets from AI creators
- Generated report with categorization
- Auto-generated by Kai 🌊"

echo -e "${BLUE}💾 Committing...${NC}"
git commit -m "${COMMIT_MSG}"

# 推送
echo -e "${BLUE}🚀 Pushing to remote...${NC}"
git push -u origin "${BRANCH_NAME}"

# 创建 PR
echo -e "${BLUE}🔀 Creating Pull Request...${NC}"
gh pr create \
    --title "📊 Daily Digest: ${DATE}" \
    --body "## AI Daily Digest - ${DATE}

自动生成的每日 AI 资讯报告。

### 📊 统计
- 报告文件: \`${REPORT_FILE}\`
- 生成时间: $(date '+%Y-%m-%d %H:%M:%S %Z')

### 🤖 自动化
本 PR 由 AI 助手 Kai 自动创建并提交。

---

查看报告：[${DATE}.md](${REPORT_FILE})" \
    --base main

echo ""
echo -e "${GREEN}✨ Publish complete!${NC}"
echo ""
echo "📋 Next steps:"
echo "  1. Review the PR"
echo "  2. Merge when ready"
echo "  3. Report will be published to main branch"
